# docker-compose.yaml
#version: '3'
services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile.node
    restart: always
    ports:
      - "4000:4000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8081:80"
    depends_on:
      - node-api
