# docker-compose.yaml
services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile.node
    restart: always
    ports:
      - "4000:4000"


  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - node-api

  vue-web:
    build:
      context: .
      dockerfile: Dockerfile.vue3
    ports:
      - "8081:80"
    depends_on:
      - node-api

  
