# Dockerfile.node
FROM node:18.18.0-alpine AS build

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiamos el archivo package.json y package-lock.json e instalamos las dependencias regulares
COPY package*.json ./
RUN npm install --omit=dev

# Copiamos el resto de los archivos de la aplicación
COPY . .

# CMD para ejecutar la aplicación directamente con Node.js
CMD ["node", "index.mjs"]
