FROM nginx:latest

# Copiar el archivo de configuración personalizado
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80
EXPOSE 80

# Verificar la configuración y reiniciar Nginx
CMD ["sh", "-c", "nginx -t && nginx -g 'daemon off;'"]
